apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app.kubernetes.io/name: fast-api
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
