name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.0-beta.2'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        

    - name: Authenticate with Google Cloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}  # Configure GCP service account key as a GitHub secret
        project_id: flask-project-427715-427716  # Replace with your GCP project ID

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy flask-project \
          --image gcr.io/flask-project-427715-427716/flaskapp:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated  # Adjust as per your requirements
